apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  ports:
    - port: 8002
  selector:
    app: auth-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service

  template:
    metadata:
      labels:
        app: auth-service
        network: internal-net

    spec:
      initContainers:
      - name: wait-for-io-service
        image: busybox:1.28
        command: ['sh', '-c', "until nc -zv io-service 8000; do echo waiting for io-service; sleep 2; done"]
      containers:
      - name: auth-service
        image: arthurp2003/remailder-auth:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: postgres-secrets
        ports:
        - containerPort: 8002
