apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config
data:
  Caddyfile: |
    {
      auto_https disable_redirects
    }

    idp-proj.go.ro:443 {
      tls internal
      reverse_proxy localhost:80
    }