apiVersion: v1
kind: Service
metadata:
  name: frontend-ui
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 443
    targetPort: 443
    name: https
  selector:
    app: frontend-ui

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-ui

  template:
    metadata:
      labels:
        app: frontend-ui
        network: public-net

    spec:
      containers:
      - name: frontend-ui
        image: arthurp2003/remailder-ui:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http

      - name: https-shield
        image: caddy:2-alpine
        command: ["sh", "-c", "echo 'idp-proj.go.ro { reverse_proxy localhost:80 }' > Caddyfile && caddy run --config Caddyfile"]
        ports:
        - containerPort: 443
          name: https
