apiVersion: v1
kind: Service
metadata:
  name: frontend-ui
spec:
  ports:
    - port: 80
  selector:
    app: frontend-ui

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-ui

  template:
    metadata:
      labels:
        app: frontend-ui
        network: public-net

    spec:
      containers:
      - name: frontend-ui
        image: arthurp2003/remailder-ui:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
