apiVersion: v1
kind: Service
metadata:
  name: io-service
spec:
  ports:
    - port: 8000
  selector:
    app: io-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: io-service
spec:
  selector:
    matchLabels:
      app: io-service
  template:
    metadata:
      labels:
        app: io-service
    spec:
      initContainers:
      - name: wait-for-postgres
        image: busybox:1.28
        command: ['sh', '-c', "until nc -zv postgres-db 5432; do echo waiting for postgres; sleep 2; done"]
      - name: wait-for-rabbitmq
        image: busybox:1.28
        command: ['sh', '-c', "until nc -zv rabbitmq-service 5672; do echo waiting for rabbitmq; sleep 2; done"]
      containers:
      - name: io-service
        image: arthurp2003/remailder-worker:latest
        envFrom:
        - secretRef:
            name: postgres-secrets
        ports:
        - containerPort: 8000