apiVersion: v1
kind: Service
metadata:
  name: main-service
spec:
  ports:
    - port: 8001
  selector:
    app: main-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-service
spec:
  selector:
    matchLabels:
      app: main-service
  template:
    metadata:
      labels:
        app: main-service
    spec:
      initContainers:
      - name: wait-for-rabbitmq
        image: busybox:1.28
        command: ['sh', '-c', "until nc -zv rabbitmq-service 5672; do echo waiting for rabbitmq; sleep 2; done"]
      containers:
      - name: main-service
        image: arthurp2003/remailder-manager:latest
        envFrom:
        - secretRef:
            name: postgres-secrets
        ports:
        - containerPort: 8001